[32m2024-03-22 09:35:52 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d5ea7ba2-5881-46ab-b885-25e179c95aff - 19671 - LOGS_CAPTURED - Started capturing logs in process (pid: 19671).
[32m2024-03-22 09:35:52 -0500[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - d5ea7ba2-5881-46ab-b885-25e179c95aff - 19671 - taxi_trips_file - STEP_START - Started execution of step "taxi_trips_file".
[32m2024-03-22 09:35:55 -0500[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - d5ea7ba2-5881-46ab-b885-25e179c95aff - 19671 - taxi_trips_file - STEP_FAILURE - Execution of step "taxi_trips_file" failed.

dagster._core.errors.DagsterExecutionStepExecutionError: Error occurred while executing op "taxi_trips_file"::

NameError: name 'constants' is not defined

Stack Trace:
  File "/Users/justinleary/dagster_venv/lib/python3.9/site-packages/dagster/_core/execution/plan/utils.py", line 54, in op_execution_error_boundary
    yield
  File "/Users/justinleary/dagster_venv/lib/python3.9/site-packages/dagster/_utils/__init__.py", line 463, in iterate_with_context
    next_output = next(iterator)
  File "/Users/justinleary/dagster_venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 131, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/Users/justinleary/dagster_venv/lib/python3.9/site-packages/dagster/_core/execution/plan/compute_generator.py", line 125, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/Users/justinleary/Git/dagster_university/dagster_university/assets/trips.py", line 15, in taxi_trips_file
    with open(constants.TAXI_TRIPS_TEMPLATE_FILE_PATH.format(month_to_fetch), "wb") as output_file:
[0m
